version: '3'
services:
  nginx:
    build:
      context: ./frontend/app
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/var/www/certbot
      - ./frontend/app/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done'"

networks:
  app-network:
    driver: bridge