name: CICD

on:
  pull_request:
    branches: [ "develop" ]
    types: [ closed ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.yml
        working-directory: ./backend
        run: |
          cd ./src/main
          mkdir resources
          cd ./resources
          touch ./application.yml
          echo "${{ secrets.YML }}" > ./application.yml
        shell: bash

      - name: Grant execution permission for gradle
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Build with Gradle Without test
        working-directory: ./backend
        run: ./gradlew clean build -x test

      - name: Docker build & push
        working-directory: ./backend
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moyeobwa -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/moyeobwa

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop moyeobwa
            docker rm moyeobwa
            docker image rm -f moyeobwa
            docker pull ${{ secrets.DOCKER_USERNAME }}/moyeobwa
            docker run -d -p 8080:8080 --name moyeobwa ${{ secrets.DOCKER_USERNAME }}/moyeobwa
