name: CI Test

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - backend/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.yml
        working-directory: ./backend
        run: |
          cd ./src/test
          mkdir resources
          cd ./resources
          touch ./application.yml
          echo "${{ secrets.TEST_YML }}" > ./application.yml
        shell: bash

      - name: Grant execution permission for gradle
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew clean build

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: backend/build/test-results/test/TEST-*.xml

      - name: add comments to a pull request
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: backend/build/test-results/test/TEST-*.xml

